site_name:        FiniteDiff.jl
repo_url:         https://github.com/johnmyleswhite/FiniteDiff.jl/
site_description: Library for numerical differentation of Julia functions.
site_author:      johnmyleswhite

theme: readthedocs

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
    - Home: 'index.md'
    - Core Functions:
        - derivative: 'core/derivative.md'
        - second_derivative: 'core/second_derivative.md'
        - gradient: 'core/gradient.md'
        - hessian: 'core/hessian.md'
    - Developer Documentation:
        - Internal Types and Functions: 'developer/internal_functions.md'
        - Code Walkthrough: 'developer/code_walkthrough.md'
    - Examples:
        - Maximum Likelihood Estimation: 'examples/mle.md'
    - Bibliography: 'bibliography.md'
    - License: 'LICENSE.md'
